# For more information: https://laravel.com/docs/sail
version: '3'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 60s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
